### ISSUE TITLE
Official example console warning of El date picker

### ISSUE THREAD

**Issue by guagezuishuai** [element-plus/element-plus#1017]
https://codepen.io/guagezuishuai/pen/RwGVwVv

文档的示例中 el-date-picker 第一个带快捷选项，再线运行，点击选择器控制台报警告

[Vue warn]: Extraneous non-props attributes (align) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <Picker format="YYYY-MM-DD" type="date" modelValue=""  ... > 
  at <ElDatePicker modelValue="" onUpdate:modelValue=fn<onUpdate:modelValue> align="right"  ... > 
  at <App>
  
  并且不会再次触发:disabled-date="disabledDate"配置的方法

**Comment by zazzaz** [comment]
the fragment error will be fixed in # 1009 soon

**Comment by JeremyWuuuuu** [comment]
Fixed in #1009. Closing.

**Comment by Bickson** [comment]
I'm on beta 27 and I just installed and still get this exact error
