### ISSUE TITLE
[Component] [upload] el-upload v-mode不生效

### ISSUE THREAD

**Issue by pk8848597** [element-plus/element-plus#10295]
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.27`
- Element Plus Version: `2.2.10`
- Browser / OS: `chrome 107`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgdi1tb2RlbDpmaWxlLWxpc3Q9XCJzdGF0ZS5maWxlTGlzdFsndGVzdCddXCJcbiAgICBhY3Rpb249XCJodHRwczovL3J1bi5tb2NreS5pby92My85ZDA1OWJmOS00NjYwLTQ1ZjItOTI1ZC1jZTgwYWQ2YzRkMTVcIlxuICAgIGxpc3QtdHlwZT1cInBpY3R1cmUtY2FyZFwiXG4gICAgOm9uLXByZXZpZXc9XCJoYW5kbGVQaWN0dXJlQ2FyZFByZXZpZXdcIlxuICAgIDpvbi1yZW1vdmU9XCJoYW5kbGVSZW1vdmVcIlxuICAgIDpvbi1jaGFuZ2U9XCJoYW5kbGVyQ2hhbmdlXCJcbiAgPlxuICAgIDxlbC1pY29uPjxQbHVzIC8+PC9lbC1pY29uPlxuICA8L2VsLXVwbG9hZD5cblxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCI+XG4gICAgPGltZyB3LWZ1bGwgOnNyYz1cImRpYWxvZ0ltYWdlVXJsXCIgYWx0PVwiUHJldmlldyBJbWFnZVwiIC8+XG4gIDwvZWwtZGlhbG9nPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmltcG9ydCB0eXBlIHsgVXBsb2FkUHJvcHMsIFVwbG9hZFVzZXJGaWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBzdGF0ZSA9IHJlYWN0aXZlKHtcbiAgZmlsZUxpc3Q6IHtcbiAgICB0ZXN0OiBbXVxuICB9XG59KVxuXG5jb25zdCBkaWFsb2dJbWFnZVVybCA9IHJlZignJylcbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5cbmNvbnN0IGhhbmRsZXJDaGFuZ2UgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKHN0YXRlLmZpbGVMaXN0KVxufVxuXG5jb25zdCBoYW5kbGVSZW1vdmU6IFVwbG9hZFByb3BzWydvblJlbW92ZSddID0gKHVwbG9hZEZpbGUsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIGNvbnNvbGUubG9nKHVwbG9hZEZpbGUsIHVwbG9hZEZpbGVzKVxufVxuXG5jb25zdCBoYW5kbGVQaWN0dXJlQ2FyZFByZXZpZXc6IFVwbG9hZFByb3BzWydvblByZXZpZXcnXSA9ICh1cGxvYWRGaWxlKSA9PiB7XG4gIGRpYWxvZ0ltYWdlVXJsLnZhbHVlID0gdXBsb2FkRmlsZS51cmwhXG4gIGRpYWxvZ1Zpc2libGUudmFsdWUgPSB0cnVlXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Element Plus version: > 2.2.9，大于这个版本的都有问题
----------------------------------- 分割线 -----------------------------------
```vue
  <el-upload
    v-model:file-list="state.fileList['test']" ==>>> 未触发向双向绑定写法 ！！！
    action="https://run.mocky.io/v3/9d059bf9-4660-45f2-925d-ce80ad6c4d15"
    list-type="picture-card"
    :on-preview="handlePictureCardPreview"
    :on-remove="handleRemove"
    :on-change="handlerChange"
  >
  </el-upload>
const state = reactive({
  fileList: {
    test: []
  }
})
const handlerChange = () => {
  console.log(state.fileList)
  // 使用2.2.9以上版本，log内两次打印（第一次上传触发，第二次上传失败删除触发）的test 数组长度都为0
  // 使用2.2.9版本，第一次打印有数组有长度，第二次删除后长度为0，数据双向绑定正常。}
```

### What is Expected?

v-model succeeded

### What is actually happening?

v-model not work

### Additional comments

_(empty)_

**Comment by Simon-He95** [comment]
@pk8848597 you can temporarily use setTimeout to get fileList in handlerChange. The next version will be fixed

**Comment by chenxch** [comment]
This issue has been fixed in #10220.

**Comment by chenxch** [comment]
some #10331

**Comment by wgh970312** [comment]
name: element-plus
version: 2.3.4

problem still exists

`
<ElUpload v-bind="$attrs" list-type="picture-card" :file-list="fileList" @update:file-list="test">
    <slot />
  </ElUpload>
...
function test(...args) {
  console.log(...args); // Not performed
}
`

**Comment by wgh970312** [comment]
name: element-plus
version: 2.3.4

problem still exists

```
<ElUpload v-bind="$attrs" list-type="picture-card" :file-list="fileList" @update:file-list="test">
 <slot /> 
</ElUpload> 
... 
function test(...args) { console.log(...args); // Not performed }
```
