### ISSUE TITLE
[Style] [All] [SASS] Deprecation Warning: color.xxx() is deprecated.

### ISSUE THREAD

**Issue by Redlnn** [element-plus/element-plus#18301]
Bug Type: **`Style`**

## Environment

- Vue Version: `3.5.6`
- Element Plus Version: `2.8.3`
- Browser / OS: `Chrome/128.0.0.0`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus-vite-starter)

### Steps to reproduce

```sh
git clone https://github.com/element-plus/element-plus-vite-starter
pnpm add -D sass@^1.79.1
pnpm build
```

### What is Expected?

没有任何错误

### What is actually happening?

```txt
Deprecation Warning: color.red() is deprecated. Suggestion:

color.channel($color, red)

More info: https://sass-lang.com/d/color-functions

   ╷
12 │   $red: color.red($upper) * $opacity + color.red($lower) * (1 - $opacity);
   │         ^^^^^^^^^^^^^^^^^
   ╵
    node_modules\.pnpm\element-plus@2.8.3_vue@3.5.6_typescript@5.6.2_\node_modules\element-plus\theme-chalk\src\color\index.scss 12:9  mix-overlay-color()
    node_modules\.pnpm\element-plus@2.8.3_vue@3.5.6_typescript@5.6.2_\node_modules\element-plus\theme-chalk\src\dark\var.scss 96:13    @forward
    src\styles\element\dark.scss 9:1
               @use
    src\styles\element\index.scss 42:1
               @use
    node_modules\.pnpm\element-plus@2.8.3_vue@3.5.6_typescript@5.6.2_\node_modules\element-plus\theme-chalk\src\tooltip.scss 1:1       root stylesheet
```

### Additional comments

_(empty)_

**Comment by selvinzr** [comment]
Unfortunately, I also encountered this issue. Although it doesn't affect the project for now, the constant warnings are quite annoying.

**Comment by Redlnn** [comment]
> have anyone found the solution?

Waiting for #18300 to be merged, ignore this warning for now

**Comment by newives** [comment]
蹲一下 最新版`SASS`不可用

**Comment by lcglcglcglcglcg** [comment]
If use npm can not get this warning, Then Whether using pnpm or npm.

**Comment by warmthsea** [comment]
https://github.com/element-plus/element-plus/pull/18376 has been fixed, you can click here to install the latest version

![image](https://github.com/user-attachments/assets/b096cb78-6fe9-4bfc-a5df-5361e245a8a5)

**Comment by lucbic** [comment]
I have upgraded the library but still getting the sass warnings

**Comment by warmthsea** [comment]
> I have upgraded the library but still getting the sass warnings

Can you provide relevant screenshots?

**Comment by Redlnn** [comment]
I think the problem you got might be this https://github.com/element-plus/element-plus/pull/18376#issuecomment-2381365324

**Comment by lvr1997** [comment]
> * 2.8.3

I have upgraded the sass but still getting the same warnings

Environment: 
Vue Version: 3.4.21
Element Plus Version: 2.8.3
Browser / OS: Chrome/128.0.0.0
Build Tool: Vite

What is actually happening?
![image](https://github.com/user-attachments/assets/04b04a6e-7313-4b95-b7f8-3d151edfdaad)

**Comment by lvr1997** [comment]
> #18376 has been fixed, you can click here to install the latest version
> 
> ![image](https://private-user-images.githubusercontent.com/45450994/371998821-b096cb78-6fe9-4bfc-a5df-5361e245a8a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MzA4MTcsIm5iZiI6MTcyODYzMDUxNywicGF0aCI6Ii80NTQ1MDk5NC8zNzE5OTg4MjEtYjA5NmNiNzgtNmZlOS00YmZjLWE1ZGYtNTM2MWUyNDVhOGE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA3MDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MjNiYjEwYmVmZTcwZDQ2M2ZhY2U2ZDdjODc3NTE2MDE5OWRlZTFjNTZhN2FhYjVhMTBmZGE3ZmViNDA3ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1k4vwd4QSLUNO-1Jr6L0AI53Vi_f5j8M-B_Xi5ouHPU)

I have upgraded the sass but still getting the same warnings

Environment:
Vue Version: 3.4.21
Element Plus Version: 2.8.3
Browser / OS: Chrome/128.0.0.0
Build Tool: Vite
![image](https://github.com/user-attachments/assets/7a4826d9-a49a-4d26-9ae1-e25250ae90ad)

**Comment by jamessandison** [comment]
I found that the 2.8.4 element plus release did not include the change when checking the source

**Comment by warmthsea** [comment]
> I found that the 2.8.4 element plus release did not include the change when checking the source

Wait for 2.5 to be released or 

![image](https://github.com/user-attachments/assets/b096cb78-6fe9-4bfc-a5df-5361e245a8a5)
