### ISSUE TITLE
[All] Sass Deprecation Warning

### ISSUE THREAD

**Issue by a81n9** [element-plus/element-plus#18759]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.5.12`
- Element Plus Version: `2.8.7`
- Browser / OS: `Chrome: 130.0.2849.68`
- Build Tool: `Vite`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdG9vbHRpcCBwbGFjZW1lbnQ9XCJ0b3BcIj5cbiAgICA8dGVtcGxhdGUgI2NvbnRlbnQ+IG11bHRpcGxlIGxpbmVzPGJyIC8+c2Vjb25kIGxpbmUgPC90ZW1wbGF0ZT5cbiAgICA8ZWwtYnV0dG9uPlRvcCBjZW50ZXI8L2VsLWJ1dHRvbj5cbiAgPC9lbC10b29sdGlwPlxuPC90ZW1wbGF0ZT5cbiJ9)

### Steps to reproduce

"element-plus": "^2.8.7",
"sass": "^1.80.6"

Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.

![image](https://github.com/user-attachments/assets/2e9b6ab5-1278-4733-a21f-15d8dfe91cce)

### What is Expected?

No SASS warning

### What is actually happening?

Existence Sass warning

### Additional comments

_(empty)_

![image](https://github.com/user-attachments/assets/2e9b6ab5-1278-4733-a21f-15d8dfe91cce)

**Comment by mxp131011** [comment]
I also have the same problem

**Comment by OVYVO** [comment]
$E:null;
$B:null;

Add the above two lines of code to 
![image](https://github.com/user-attachments/assets/5dac4d26-e67d-4ddb-99a5-eba145ab0444)
this file.
But this can only handle local project runtime errors. Building the project online may require other ways to solve it, and I am still looking for a solution

**Comment by warmthsea** [comment]
fixed in https://github.com/element-plus/element-plus/pull/18711, can do this install new version:

![screenshots](https://github.com/user-attachments/assets/8ec28109-2391-4e82-85dc-51af50d1835c)

**Comment by a81n9** [comment]
@warmthsea 
I tested version 2.8.8 today still exist in Sass warning.

```
Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
```

![image](https://github.com/user-attachments/assets/6f433c28-18b1-4572-94a5-275616b313b2)

**Comment by warmthsea** [comment]
> @warmthsea 
> 
> I tested version 2.8.8 today still exist in Sass warning.
> 
> 
> 
> ```
> 
> Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0.
> 
> ```
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/6f433c28-18b1-4572-94a5-275616b313b2)
> 
> 

Refer to:  
https://github.com/element-plus/element-plus/pull/18428/files

**Comment by warmthsea** [comment]
@LiXunGuan 

https://vite.dev/config/shared-options.html#css-preprocessoroptions

or

vite.config.ts
```ts
css: {
  preprocessorOptions: {
    scss: {
      silenceDeprecations: ['legacy-js-api'],
    },
  },
},
```
