### ISSUE TITLE
[bug report] using El form item component, the console reports an error elementpluserror: [util] binding value must be a string or number

### ISSUE THREAD

**Issue by gowiny** [element-plus/element-plus#2557]
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
window 10/firefox 89.0.2

### Vue version
3.1.5

### Reproduction Link
https://elementui.github.io/issue-generator/#/en-US?repo=element-plus

### Steps to reproduce
<template>
  <el-form :inline="true" :model="formInline" class="demo-form-inline">
  <el-form-item label="审批人">
    <el-input v-model="formInline.user" placeholder="审批人"></el-input>
  </el-form-item>
  <el-form-item label="活动区域">
    <el-select v-model="formInline.region" placeholder="活动区域">
      <el-option label="区域一" value="shanghai"></el-option>
      <el-option label="区域二" value="beijing"></el-option>
    </el-select>
  </el-form-item>
  <el-form-item>
    <el-button type="primary" @click="onSubmit">查询</el-button>
  </el-form-item>
</el-form>
</template>

<script>

export default {
    data() {
      return {
        formInline: {
          user: '',
          region: ''
        }
      }
    },
    methods: {
      onSubmit() {
        console.log('submit!');
      }
    }
  }
</script>

------------------
直接复制的文档里的代码，打开页面，页面能正常显示，
但是控制台里报错：
ElementPlusError: [Util] binding value must be a string or number

### What is Expected?
请把这个错误解决

### What is actually happening?
直接复制的文档里的代码，打开页面，页面能正常显示，
但是控制台里报错：
ElementPlusError: [Util] binding value must be a string or number

**Comment by kooriookami** [comment]
Fixed in next version. #2492

**Comment by norangit** [comment]
the error is still there in version 1.0.2 - 55, it is not fixed

**Comment by kooriookami** [comment]
> the error is still there in version 1.0.2 - 55, it is not fixed

next version means 1.0.2-beta.56, we haven't release it.
