### ISSUE TITLE
[Bug Report] The Cascader component start to be unresponsive after several clicks.

### ISSUE THREAD

**Issue by tolbxela** [element-plus/element-plus#3399]
### Element Plus version
1.1.0-beta.10

### OS/Browsers version
Windows / Edge & Chrome

### Vue version
3.2.11

### Reproduction Link
https://jsfiddle.net/ra9weLd7/

### Steps to reproduce
Perform in cycle several focus changing clicks on the Cascader component and otherwhere. After some amount of clicks the control stops responding and the web page hangs. 

### What is Expected?
The Cascader component should not hang.

### What is actually happening?
The Cascader component start to be unresponsive after several clicks.

Here is the screen recording describing the problem:

![EP_Cascader_Hang](https://user-images.githubusercontent.com/4910589/133248399-79fdb75b-2aaa-42a3-affb-7711959fdc19.gif)

Does occur on:

- Chrome

![image](https://user-images.githubusercontent.com/4910589/133250125-48746442-33e4-4f12-9538-54661d65fe9b.png)

- Edge

![image](https://user-images.githubusercontent.com/4910589/133250174-db0dd669-4127-43ed-92f6-c69f23451965.png)

**Does not occur on Brave with Chromium 91 Version**
![image](https://user-images.githubusercontent.com/4910589/133250809-200d7a6d-66dc-4360-8e65-ed1dfab445e3.png)

**Comment by lazy-senior** [comment]
Also having this Issue

**Comment by adaex** [comment]
On my computer (macOS 11.5.2), the problem does not occur with either chrome(93.0.4577.63) or safari(14.1.2), we may need more information to determine if it is just in windows.

**Comment by Xdy1579883916** [comment]
或许是需要暂时关闭vue的浏览器插件,我发现它死循环了

**Comment by tolbxela** [comment]
> 或许是需要暂时关闭vue的浏览器插件,我发现它死循环了

This one is a bit hard to read 😄

**Comment by Shigma** [comment]
I can reproduce it on both windows and macos.

**Comment by adaex** [comment]
> I can reproduce it on both windows and macos.

@Shigma  Can you find out what's causing this problem?  Is it possible that it's because of the Vue Dev Tools Plugin?

**Comment by tolbxela** [comment]
I have tested it on Edge without plugin installed and still had the same problem.

**Comment by xiaoxian521** [comment]
@tolbxela 
You can disable Vue Devtools in Google Chrome and try again
I can't reproduce it on mac

**Comment by tolbxela** [comment]
@xiaoxian521 did it already with the same result. I guess it is not related to the vue dev plugin.

**Comment by Shigma** [comment]
@adaex actually I did not install Vue DevTools at all

**Comment by flmbbb** [comment]
速度解决啊。。我也被这个问题搞疯了了。。。

**Comment by tolbxela** [comment]
Is this bug related to **[bug report] cascade selector of cascader is stuck after clicking or selecting several times** (#3543) ?

**Comment by xiaoxian521** [comment]
> Is this bug related to **[bug report] cascade selector of cascader is stuck after clicking or selecting several times** (#3543) ?

yes, has been fixed.

**Comment by tolbxela** [comment]
@xiaoxian521 No, it is not fixed. unfortunately 😞 

Captured right now with Microsoft Edge
Version 93.0.961.52 (Official build) (64-bit) without Vue Dev Plugin

![EP_Cascader_Hang_2](https://user-images.githubusercontent.com/4910589/134487328-b4410285-21bf-4495-b356-7021b0118089.gif)

**Comment by tolbxela** [comment]
@xiaoxian521 yes, it is solved. 👍 
Thanks a lot! 🙇
