### ISSUE TITLE
Unhandled error during execution of render function    at <ElScrollbar key="hours" ref="listHoursRef" class="el-time-spinner__wrapper"  ... > 

### ISSUE THREAD

**Issue by denyncrawford** [element-plus/element-plus#606]
Hi!!! I'm just trying to reproduce the [component form absic example](https://element-plus.org/#/es/component/form) and it renders just nice. 

This is my wiew: 
![view](https://user-images.githubusercontent.com/28849055/99280581-42c92b80-2810-11eb-9bd1-cc97b0d0c285.png)

The problem is that as soon as you click on the time picker, the following error appears with the following warnings:

```sh
runtime-dom.esm-bundler-992962aa.js:1176 [Vue warn]: Unhandled error during execution of render function 
  at <ElScrollbar key="hours" ref="listHoursRef" class="el-time-spinner__wrapper"  ... > 
  at <Anonymous ref="spinner" role="start" arrow-control=false  ... > 
  at <BaseTransition appear=false persisted=false onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" type="time" default-value=undefined  ... > 
  at <Anonymous visible=true parsed-value=undefined format="HH:mm:ss"  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=false  ... > 
  at <Transition name="el-fade-in-linear" onAfter-enter=fn<onAfterEnter> onAfter-leave=fn<onAfterLeave> > 
  at <ElPopper ref="popper" visible=true onUpdate:visible=fn  ... > 
  at <Picker format="HH:mm:ss" isRange=false type="time"  ... > 
  at <ElTimePicker placeholder="Pick a time" modelValue="" onUpdate:modelValue=fn  ... > 
  at <ElCol span=11 > 
  at <ElFormItem label="Activity time" > 
  at <ElForm ref="form" model= 
{name: "", region: "", date1: "", date2: "", delivery: false, …}
 label-width="120px" > 
  at <Page title="Ingresar corte" > 
  at <Nuevo class="flex-grow overflow-auto" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy {onSubmit: ƒ, …}
 > > 
  at <RouterView class="flex-grow overflow-auto" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="slide" mode="out-in" > 
  at <App>
runtime-dom.esm-bundler-992962aa.js:1176 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/vue-next 
  at <ElScrollbar key="hours" ref="listHoursRef" class="el-time-spinner__wrapper"  ... > 
  at <Anonymous ref="spinner" role="start" arrow-control=false  ... > 
  at <BaseTransition appear=false persisted=false onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" type="time" default-value=undefined  ... > 
  at <Anonymous visible=true parsed-value=undefined format="HH:mm:ss"  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=false  ... > 
  at <Transition name="el-fade-in-linear" onAfter-enter=fn<onAfterEnter> onAfter-leave=fn<onAfterLeave> > 
  at <ElPopper ref="popper" visible=true onUpdate:visible=fn  ... > 
  at <Picker format="HH:mm:ss" isRange=false type="time"  ... > 
  at <ElTimePicker placeholder="Pick a time" modelValue="" onUpdate:modelValue=fn  ... > 
  at <ElCol span=11 > 
  at <ElFormItem label="Activity time" > 
  at <ElForm ref="form" model= 
{name: "", region: "", date1: "", date2: "", delivery: false, …}
 label-width="120px" > 
  at <Page title="Ingresar corte" > 
  at <Nuevo class="flex-grow overflow-auto" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy {onSubmit: ƒ, …}
 > > 
  at <RouterView class="flex-grow overflow-auto" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="slide" mode="out-in" > 
  at <App>
runtime-dom.esm-bundler-992962aa.js:1176 [Vue warn]: Property "popperRef" was accessed during render but is not defined on instance. 
  at <ElScrollbar key="hours" ref="listHoursRef" class="el-time-spinner__wrapper"  ... > 
  at <Anonymous ref="spinner" role="start" arrow-control=false  ... > 
  at <BaseTransition appear=false persisted=false onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" type="time" default-value=undefined  ... > 
  at <Anonymous visible=true parsed-value=undefined format="HH:mm:ss"  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=false  ... > 
  at <Transition name="el-fade-in-linear" onAfter-enter=fn<onAfterEnter> onAfter-leave=fn<onAfterLeave> > 
  at <ElPopper ref="popper" visible=true onUpdate:visible=fn  ... > 
  at <Picker format="HH:mm:ss" isRange=false type="time"  ... > 
  at <ElTimePicker placeholder="Pick a time" modelValue="" onUpdate:modelValue=fn  ... > 
  at <ElCol span=11 > 
  at <ElFormItem label="Activity time" > 
  at <ElForm ref="form" model= 
{name: "", region: "", date1: "", date2: "", delivery: false, …}
 label-width="120px" > 
  at <Page title="Ingresar corte" > 
  at <Nuevo class="flex-grow overflow-auto" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy {onSubmit: ƒ, …}
 > > 
  at <RouterView class="flex-grow overflow-auto" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="slide" mode="out-in" > 
  at <App>
runtime-dom.esm-bundler-992962aa.js:1176 [Vue warn]: Property "popperRef" was accessed during render but is not defined on instance. 
  at <ElScrollbar key="hours" ref="listHoursRef" class="el-time-spinner__wrapper"  ... > 
  at <Anonymous ref="spinner" role="start" arrow-control=false  ... > 
  at <BaseTransition appear=false persisted=false onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" type="time" default-value=undefined  ... > 
  at <Anonymous visible=true parsed-value=undefined format="HH:mm:ss"  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=false  ... > 
  at <Transition name="el-fade-in-linear" onAfter-enter=fn<onAfterEnter> onAfter-leave=fn<onAfterLeave> > 
  at <ElPopper ref="popper" visible=true onUpdate:visible=fn  ... > 
  at <Picker format="HH:mm:ss" isRange=false type="time"  ... > 
  at <ElTimePicker placeholder="Pick a time" modelValue="" onUpdate:modelValue=fn  ... > 
  at <ElCol span=11 > 
  at <ElFormItem label="Activity time" > 
  at <ElForm ref="form" model= 
{name: "", region: "", date1: "", date2: "", delivery: false, …}
 label-width="120px" > 
  at <Page title="Ingresar corte" > 
  at <Nuevo class="flex-grow overflow-auto" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy {onSubmit: ƒ, …}
 > > 
  at <RouterView class="flex-grow overflow-auto" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="slide" mode="out-in" > 
  at <App>
runtime-dom.esm-bundler-992962aa.js:1176 [Vue warn]: Property "popperRef" was accessed during render but is not defined on instance. 
  at <ElScrollbar key="hours" ref="listHoursRef" class="el-time-spinner__wrapper"  ... > 
  at <Anonymous ref="spinner" role="start" arrow-control=false  ... > 
  at <BaseTransition appear=false persisted=false onBeforeEnter=fn<onBeforeEnter>  ... > 
  at <Transition name="el-zoom-in-top" type="time" default-value=undefined  ... > 
  at <Anonymous visible=true parsed-value=undefined format="HH:mm:ss"  ... > 
  at <BaseTransition onAfterEnter=fn<onAfterEnter> onAfterLeave=fn<onAfterLeave> appear=false  ... > 
  at <Transition name="el-fade-in-linear" onAfter-enter=fn<onAfterEnter> onAfter-leave=fn<onAfterLeave> > 
  at <ElPopper ref="popper" visible=true onUpdate:visible=fn  ... > 
  at <Picker format="HH:mm:ss" isRange=false type="time"  ... > 
  at <ElTimePicker placeholder="Pick a time" modelValue="" onUpdate:modelValue=fn  ... > 
  at <ElCol span=11 > 
  at <ElFormItem label="Activity time" > 
  at <ElForm ref="form" model= 
{name: "", region: "", date1: "", date2: "", delivery: false, …}
 label-width="120px" > 
  at <Page title="Ingresar corte" > 
  at <Nuevo class="flex-grow overflow-auto" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< 
Proxy {onSubmit: ƒ, …}
 > > 
  at <RouterView class="flex-grow overflow-auto" > 
  at <BaseTransition mode="out-in" appear=false persisted=false  ... > 
  at <Transition name="slide" mode="out-in" > 
  at <App>
element-plus.js:35 Uncaught (in promise) TypeError: Cannot read property 'hour' of undefined
    at element-plus.js:35
    at ComputedRefImpl.reactiveEffect [as effect] (runtime-dom.esm-bundler-992962aa.js:339)
    at ComputedRefImpl.get value [as value] (runtime-dom.esm-bundler-992962aa.js:1116)
    at element-plus.js:35
    at renderList (runtime-dom.esm-bundler-992962aa.js:7916)
    at element-plus.js:35
    at renderFnWithContext (runtime-dom.esm-bundler-992962aa.js:2561)
    at renderSlot (runtime-dom.esm-bundler-992962aa.js:2538)
    at element-plus.js:29
    at renderFnWithContext (runtime-dom.esm-bundler-992962aa.js:2561)
```

And when you blur it the console shows:

```sh
runtime-dom.esm-bundler-992962aa.js:7999 Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
    at insert (runtime-dom.esm-bundler-992962aa.js:7999)
    at processCommentNode (runtime-dom.esm-bundler-992962aa.js:4715)
    at patch (runtime-dom.esm-bundler-992962aa.js:4667)
    at componentEffect (runtime-dom.esm-bundler-992962aa.js:5255)
    at Object.reactiveEffect [as update] (runtime-dom.esm-bundler-992962aa.js:339)
    at updateComponent (runtime-dom.esm-bundler-992962aa.js:5144)
    at processComponent (runtime-dom.esm-bundler-992962aa.js:5078)
    at patch (runtime-dom.esm-bundler-992962aa.js:4685)
    at componentEffect (runtime-dom.esm-bundler-992962aa.js:5255)
    at Object.reactiveEffect [as update] (runtime-dom.esm-bundler-992962aa.js:339)
```

The timepicker does't show anything. (The datepicker shows the calendar).

**My view file is an exact copy of the example above**.

And this is my vue `main.js` file:

```js
import { createApp } from 'vue'
import App from './App.vue'
import './index.scss'
import ElementUI from 'element-plus';
import 'element-plus/lib/theme-chalk/index.css';
import 'element-plus/lib/theme-azure/index.css';
import locale from 'element-plus/lib/locale/lang/es'
import router from './router'
import './assets/styles/index.css'
import store from './store';

const electron = require('electron')
const ipc = electron.ipcRenderer

ipc.send('store:set', { key: 'foo.bar', value: '👩' })
ipc.invoke('store:get', 'foo').then((res) => {
    console.log(res)
})
ipc.send('store:delete', 'foo')
ipc.invoke('store:get', 'foo').then((res) => {
    console.log(res)
})

const app = createApp(App)

app.use(router)
app.use(store)
app.use(ElementUI, { locale })
app.mount('#app')

```

Also, the datepicker doesn't seem to throw any error, but when selecting the date, it is not rendering or updating the datepicker view but in the component's data object, it does, so it is not a big issue, but is anoying hahah.

I need some help to make it work :/ 

I'm runing vite and electron with [vite-electron-cli](https://github.com/MangoTsing/vite-electron-cli#readme);

If you need something more just tell me, thanks.

**Comment by JeremyWuuuuu** [comment]
@zazzaz can you take a look?

**Comment by zazzaz** [comment]
will do

**Comment by zazzaz** [comment]
Any demo code please?

**Comment by denyncrawford** [comment]
This is my datepicker component:
![code](https://user-images.githubusercontent.com/28849055/99520453-debe7880-2971-11eb-8519-25551d80d7ea.png)
![code](https://user-images.githubusercontent.com/28849055/99520776-4d033b00-2972-11eb-8447-e171614ff828.png)
And as you can see, a date is selected but no data is showed on the input.
And this is the time picker:
```js
<el-time-picker placeholder="Pick a time" v-model="form.date2" style="width: 100%;"></el-time-picker>
```
And the error message is the one above.

Actually I'm not using it anymore. I'm using timeselect instead and is working perfect.

**Comment by zazzaz** [comment]
Can you please try the code in this answer? https://github.com/element-plus/element-plus/issues/603#issuecomment-729542874

I've tested it and seems fine

**Comment by denyncrawford** [comment]
> 
> 
> Can you please try the code in this answer? [#603 (comment)](https://github.com/element-plus/element-plus/issues/603#issuecomment-729542874)
> 
> I've tested it and seems fine

Nope. It didn't work like that either :/.

**Comment by JeremyWuuuuu** [comment]
So the binding seems good, but the value was not presented to the view, it needs to be fixed ASAP

**Comment by JeremyWuuuuu** [comment]
We are already looking into this issue, will fix this one in a short time

**Comment by denyncrawford** [comment]
Thank you guys, I'll be up to test it when is ready!!

**Comment by JeremyWuuuuu** [comment]
UPDATES: if you were using `Vue` with version higher than "3.0.0", then you probably won't get it work since this is a bug from `Vue`, they have made changes against `EventEmitting`, we are not be able to help with that, so for now you might want to stick your `Vue` version to `3.0.0`, remove the `^` symbol from your version field, run `rm -rf node_modules` then bootstrap your project again via `yarn` or `npm install` that should do the trick.

**Comment by JeremyWuuuuu** [comment]
Right now we can only wait until `Vue` fix the bug themselves. You might want to refer to the bug at https://github.com/vuejs/vue-next/issues/2540

**Comment by bastarder** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Comment by zazzaz** [comment]
this is a Vue bug and has been fixed in the current release `Vue 3.0.2`

**Comment by aquarmarine** [comment]
My version is Vue 3.0.4,but I still have this problem.How to solve it?

**Comment by aquarmarine** [comment]
My version is 3.0.4,but I still have this problem.How to solve it?

**Comment by JeremyWuuuuu** [comment]
@aquarmarine can you tell me how to reproduce it? cc @SimonaliaChen

**Comment by XingXiaoWu** [comment]
> @aquarmarine can you tell me how to reproduce it? cc @SimonaliaChen

I reproduced it.

You can use el-select and change options in onMounted to reproduced it.

And update to Vue 3.0.5 can fixed it

**Comment by Thy3634** [comment]
My version is 3.0.5,but I still have this problem.
