### ISSUE TITLE
When I import element-plus,vite will not be reload

### ISSUE THREAD

**Issue by cn-Meepo** [element-plus/element-plus#620]
When I import element-plus,vite will not be reload

**Comment by zazzaz** [comment]
You can check this as a reference https://github.com/element-plus/element-plus-vite-starter

**Comment by cn-Meepo** [comment]
@zazzaz this item also can not be reload

**Comment by zazzaz** [comment]
This is an interesting bug. 

I tried myself and it seems something has blocked the hot module replacement in Vite. 

Not sure if it is a bug in Vite or in Element Plus.

Will keep an eye on it.

**Comment by JeremyWuuuuu** [comment]
This might have something to do with #659

**Comment by zazzaz** [comment]
will fix soon

**Comment by zazzaz** [comment]
fixed in 1.0.1-alpha.21, thanks

**Comment by cn-Meepo** [comment]
@zazzaz   somewhere is fixed,but when i use form,the  '<el-form-item label="账号">'  label changed, it is not be reload

**Comment by ngekoding** [comment]
@zazzaz sorry, but the HMR still not working with Vite. I just try to use https://github.com/element-plus/element-plus-vite-starter

Can you try it?

**Comment by nickngqs** [comment]
as long as import ElementPlus from 'element-plus' is used, HMR will never work with Vite.   Version: ^1.0.2-beta.45

**Comment by ngekoding** [comment]
Well, after many try I found that `vite-plugin-style-import` causing the problem, so for the temporary solution, I manually import the component & css file.

For example to use el-button component:

```js
import ElButton from 'element-plus/lib/el-button'
import 'element-plus/lib/theme-chalk/el-button.css' // no problem with scss file

app.use(ElButton)
```
And the HMR keep working!

:: Still hope any simpler solution

**Comment by nickngqs** [comment]
> ```js
> import ElButton from 'element-plus/lib/el-button'
> ```

No, I think the problem is with El-Table. I think a pull request is sent to fix the el-table but not merged. Check out this #2107, #2077.

You can confirm el-table is the issue by doing this
```js
import ElTable from 'element-plus/lib/el-table'

app.use(ElTable)
```

Currently I'm using beta.44, lets wait for them to merged the fix

**Comment by ngekoding** [comment]
> > ```js
> > import ElButton from 'element-plus/lib/el-button'
> > ```
> 
> No, I think the problem is with El-Table. I think a pull request is sent to fix the el-table but not merged. Check out this #2107, #2077.
> 
> You can confirm el-table is the issue by doing this. Since importing ElementPlus includes the ElTable, it will not work in Vite HMR.
> 
> ```js
> import ElTable from 'element-plus/lib/el-table'
> 
> app.use(ElTable)
> // Vite HMR will not work
> ```
> 
> Currently I'm using beta.44, lets wait for them to merge the fix

I try to remove ElTable but still not working, do you think I must remove others components also?

**Comment by nickngqs** [comment]
@ngekoding How are you removing the el-table?

**Comment by ngekoding** [comment]
@nickngqs I just not importing it.

**Comment by nickngqs** [comment]
Are you doing this 
import ElementPlus from 'element-plus' ?

**Comment by ngekoding** [comment]
@nickngqs No, I just follow the docs how to import on demand.

Here my code looks like, just commenting the ElTable & ElTableColumn:

```
import {
  ...
  ElSwitch,
  ElTabPane,
  // ElTable,
  // ElTableColumn,
  ...
} from 'element-plus';
```

**Comment by ngekoding** [comment]
@nickngqs I was trying with Vue CLI, and the HMR not working also when using ElTable component. I just try some components: ElButton, ElSelect & ElOption no problem.
