### ISSUE TITLE
[Bug Report] [All] Uncaught SyntaxError: The requested module '/_nuxt/node_modules/dayjs/dayjs.min.js?v=391d0c11' does not provide an export named 'default' (at picker2.mjs?v=391d0c11:2:8)

### ISSUE THREAD

**Issue by melrefaie** [element-plus/element-plus#8165]
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/wizardly-wilbur-e7ngpy?file=/app.vue:0-1097)

### Steps to reproduce

add element-plus to fresh nuxt project. 
example in codesandbox 
https://codesandbox.io/s/wizardly-wilbur-e7ngpy?file=/app.vue:0-1097

### What is Expected?

expected to work in development with no errors.
it works fine in build.

### What is actually happening?

what happen that i got this error 

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/dayjs/dayjs.min.js?v=391d0c11' does not provide an export named 'default' (at picker2.mjs?v=391d0c11:2:8)
```
you can see error in console 
https://e7ngpy.sse.codesandbox.io/

and js dont work.
components appear fine but not working.

### Additional comments

I tried starter repo but it have issues.
https://github.com/element-plus/element-plus-nuxt-starter/issues/34

**Comment by tolking** [comment]
May be fixed in #8144 , you can try the latest version v2.2.5

**Comment by KahrLu** [comment]
still have the same issue, I have the version 2.2.13 running dev locally

**Comment by lvbaiying** [comment]
still have the same issue, I have the version 2.2.14 running dev locally

**Comment by BitRayDev** [comment]
still have the same issue, I have the version 2.2.17 running dev locally

**Comment by wxxwtt** [comment]
still have the same issue, I have the version 2.2.17 running dev locally

**Comment by chaselen** [comment]
still have the same issue, I have the version 2.2.18 running dev locally

**Comment by tolking** [comment]
The error cannot be reproduced using the [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter)

**Comment by chaselen** [comment]
@tolking 重现办法

`package.json`

```json
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "3.0.0-rc.11",
    "unplugin-vue-components": "^0.22.8"
  },
  "dependencies": {
    "element-plus": "^2.2.18"
  }
}
```

`nuxt.config.ts`

```typescript
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'

export default defineNuxtConfig({
  build: {
    transpile: ['element-plus/es']
  },
  vite: {
    plugins: [
      Components({
        resolvers: [ElementPlusResolver()]
      })
    ]
  }
})
```

`app.vue`

```vue
<template>
  <div>
    <el-button type="primary">test</el-button>
  </div>
</template>
```

**Comment by tolking** [comment]
Currently, the dayjs is based on CommonJS Modules. It seems that there is a conflict when you use `unplugin-vue-components` like this. Maybe you need to manually introduce required components like [template](https://github.com/element-plus/element-plus-nuxt-starter). Wait for the dayjs dependency upgrade to 2.0.

**Comment by zhang20084** [comment]
still have the same issue, I have the version 2.2.19 running dev locally

**Comment by georginklv** [comment]
Still have this issue!

**Comment by tolking** [comment]
I can not reproduce this issue in the [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter), can you provide an demo?

**Comment by AnzhiZhang** [comment]
I still have this issue on 2.3.7, and I check code in element plus, there are still some improts like `import type { Dayjs } from 'dayjs'`

**Comment by yunimm** [comment]
still have the same issue, I have the version 3.6.2 running dev locally

**Comment by Gutwql** [comment]
still have the same issue, I have the version 2.4.1 running dev locally

**Comment by hardik-wts** [comment]
node = 18.18.2
os = macOS big sur 11.6.3
Version Details 
```
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/google-fonts": "^3.0.2",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.2",
    "nuxt": "^3.7.0"
  },
  "dependencies": {
    "@element-plus/nuxt": "^1.0.5",
    "@iconify/json": "^2.2.116",
    "@nuxt/ui": "^2.8.1",
    "@pinia/nuxt": "^0.4.11",
    "bootstrap": "^5.2.3",
    "pinia": "^2.1.6",
    "sass": "^1.66.1",
    "sass-loader": "^13.3.2",
    "vue-select": "^3.20.2",
    "vue3-otp-input": "^0.4.1"
  },
```

I still am facing same proble in `postinstall` command 

 ```
Using default Tailwind CSS file                                                                     nuxt:tailwindcss 12:34:14 AM

 ERROR  Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function             12:34:15 AM


 ERROR  _dayjs.default.extend is not a function                                                                         12:34:15 AM

  at node_modules/element-plus/es/components/time-picker/src/time-picker.mjs:10:16
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at node_modules/element-plus/es/components/time-picker/index.mjs:1:2184
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at node_modules/element-plus/es/components/calendar/src/date-table.mjs:2:1
  at evalModule (node_modules/jiti/dist/jiti.js:1:255614)
  at jiti (node_modules/jiti/dist/jiti.js:1:253542)
  at node_modules/element-plus/es/components/calendar/src/date-table2.mjs:3:18 



 ERROR  _dayjs.default.extend is not a function                                                                         12:34:15 AM

npm ERR! code 1
npm ERR! path my-project-path
npm ERR! command failed
npm ERR! command sh -c nuxt prepare

npm ERR! A complete log of this run can be found in: /Users/lenovo/.npm/_logs/2023-10-25T19_04_09_552Z-debug-0.log
```

**Comment by ralix** [comment]
same issue in a new nuxt project,   any solution? 

ERROR  Error while requiring module @element-plus/nuxt: TypeError: _dayjs.default.extend is not a function                   19:21:46


 ERROR  Cannot start nuxt:  _dayjs.default.extend is not a function                                                           19:21:46

  at <anonymous> (packages/components/time-picker/src/time-picker.tsx:9:14)
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/element-plus/es/components/time-picker/index.mjs:1:2184
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/element-plus/es/components/calendar/src/date-table.mjs:2:1
  at evalModule (node_modules/jiti/dist/jiti.js:1:256443)
  at jiti (node_modules/jiti/dist/jiti.js:1:254371)
  at node_modules/element-plus/es/components/calendar/src/date-table2.mjs:3:18

**Comment by wangyewei** [comment]
there is still the original problem, why was this issue closed?

**Comment by tolking** [comment]
I've never reproduced this issue. You can use [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter) testing, or provide a demo that can reproduce this issue.

**Comment by AnzhiZhang** [comment]
I've reproduced it here: https://stackblitz.com/edit/github-spueta?file=app.vue
Please note that the code about time picker is in `app.vue`:

```html
<ElDatePicker />
```

Also, there are two `package-lock.json` file, one is named as `package-lock-backup.json`. This issue will be reproduced with `package-lock.json` and not with `package-lock-backup.json`

Commands:

```cmd
rm -r node_modules .nuxt
npm i
npx nuxt prepare
```

**Comment by tolking** [comment]
Sorry, I am unable to run the demo you provided properly. (macos 14, node 21.2.0)

```
Cannot find module './shared/untyped.a47b2336.cjs'
```

When I convert the `package-lock.json` file through `pnpm import`, it can run normally in pnpm.

```
pnpm import package-lock.json
```

//.npmrc

```
shamefully-hoist=true
strict-peer-dependencies=false
shell-emulator=true
legacy-peer-deps=true
```

Since you have provided a lock file that run normally, perhaps the cause of the issues is related to the installation dependencies.

**Comment by AnzhiZhang** [comment]
Please reproduce it in stackblitz, I also cannot reproduce it on local machine.

Yes I agree that may related to dependencies, and the elemen-plus version remains the same, but it's hard to locate the issue.

**Comment by beerui** [comment]
在nuxt.config.ts中，加入配置项 
```
export default defineNuxtConfig({
  ssr: true,
  build: {
    transpile: ['element-plus/es', 'loadsh'],
  },
})
```
这个对我有用！
我的版本是：`"element-plus": "^2.6.1", "@element-plus/nuxt": "^1.0.7",`

**Comment by tolking** [comment]
If you encounter this problem, you can try adding dayjs to the size configuration

```ts
export default defineNuxtConfig({
vite: {
    optimizeDeps: {
      include: ['dayjs', 'dayjs/plugin/*']
    }
  }
})
```

**Comment by chhumsina** [comment]
> dayjs



> If you encounter this issues, you can try adding `dayjs` to the `nuxt.config`
> 
> ```ts
> export default defineNuxtConfig({
> vite: {
>     optimizeDeps: {
>       include: ['dayjs', 'dayjs/plugin/*']
>     }
>   }
> })
> ```

It's still keep the same issue.

**Comment by pamenary** [comment]
It still keeps the same issue.

- Operating System: Darwin
- Node Version:     v21.4.0
- Nuxt Version:     3.11.2
- Element plus:    2.7.0
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.0.1

**Comment by Droppix** [comment]
same error

**Comment by pablosebastianr** [comment]
Please reproduce it in stackblitz, I also cannot reproduce it on local machine.
> 
> ![image](https://private-user-images.githubusercontent.com/37402126/298284293-6dbbc346-2a3d-44b1-99ae-97fcde4586ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODA4MDgsIm5iZiI6MTcxMzM4MDUwOCwicGF0aCI6Ii8zNzQwMjEyNi8yOTgyODQyOTMtNmRiYmMzNDYtMmEzZC00NGIxLTk5YWUtOTdmY2RlNDU4NmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5MDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDAyMWIwZDEyMjkzYjAzZDI2OWY3MmI5YTM2NTRiYjAyNTkyMWNjYmY1MjNkMTczMmY2MzRjMmEwYmNhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.awpqyW1GqgI-WL6UFHkeUTCC9tFvwbx2vOHJgUKi8Dw)
> 
> Yes I agree that may related to dependencies, and the elemen-plus version remains the same, but it's hard to locate the issue.

If I update the dependencies on my nuxt 3 project I  get this error

Currently, I have version 3.11.2 of Nuxt 3, with element-plus/nuxt@1.0.7, wich pulls element-plus@2.5.5

But the update gives me element-plus/nuxt@1.0.8 with element-plus@2.7.0 which doesn't work and blows up just like the error in the image above.

dayjs is the same, 1.11.10

**Comment by alaxcc** [comment]
I fixed it, I can't just use element-plus or dayjs-nuxt model, you need install dayjs too, 

pnpm install dayjs 

and fix.

**Comment by hefeng6500** [comment]
Add follow config to your tsconfig.json! it is resolved for me!

```json
// tsconfig.json
{
    "allowSyntheticDefaultImports": true,
    "allowImportingTsExtensions": true
}
```

**Comment by lucbic** [comment]
That didn't do the trick for me...

Is anybody else still having the same issue?

**Comment by fallenleavesss** [comment]
Running 'pnpm install dayjs' is useful

**Comment by lucbic** [comment]
For those who are still struggling with this nasty problem, migrating from pnpm to yarn 4 solved the issue for me

**Comment by kapok-jose** [comment]
> 运行“pnpm install dayjs”很有用

亲测可以

**Comment by sav4n** [comment]
i had to update nuxt to version 3.14.159 (latest)

**Comment by viocha** [comment]
This bug still exists in the current version 2.10.2
```
 WARN  Failed to resolve dependency: dayjs, present in client 'optimizeDeps.include'        11:55:55  


[11:55:55]  WARN  Failed to resolve dependency: lodash-unified, present in client 'optimizeDeps.include'
```

**Comment by bbchuoo** [comment]
Version 2.10.2 has the same issue. This problem has been around for three years. Can someone help resolve it? Thank you. It's really very troublesome.

**Comment by oommgg** [comment]
when I upgraded nuxt 4.1.3 to 4.2.0 got this problem.
I solved by adding:

```javascript
//nuxt.config.ts
export default defineNuxtConfig({
  alias: {
    dayjs: 'dayjs',
  }
})
```

**Comment by leoding86** [comment]
> when I upgraded nuxt 4.1.3 to 4.2.0 got this problem. I solved by adding:
> 
> //nuxt.config.ts
> export default defineNuxtConfig({
>   alias: {
>     dayjs: 'dayjs',
>   }
> })

Fixed my problem.

**Comment by Vandomeri** [comment]
> when I upgraded nuxt 4.1.3 to 4.2.0 got this problem. I solved by adding:
> 
> //nuxt.config.ts
> export default defineNuxtConfig({
>   alias: {
>     dayjs: 'dayjs',
>   }
> })

Thanks a lot!
